adjectives = [
    "abundant", "absurd", "acrobatic", "adorable", "adventurous", "agile", "agitated", "alarming", "aloof",
    "ambitious", "amused", "angry", "animated", "annoying", "anxious", "apathetic", "arrogant", "artful",
    "ashamed", "astonishing", "attractive", "audacious", "awesome", "awkward", "baffled", "bald", "bawdy",
    "beautiful", "belligerent", "bewildered", "big-headed", "blissful", "bloated", "boastful", "boisterous", 
    "bold", "bossy", "brainless", "brave", "breezy", "brilliant", "broke", "brooding", "brutal", "bubbly", 
    "bug-eyed", "bumbling", "burly", "busty", "buzzing", "calm", "candid", "carefree", "careless", "caring",
    "charming", "cheeky", "cheerful", "chesty", "chilled", "chivalrous", "chubby", "classy", "clueless", 
    "clumsy", "cocky", "comical", "compassionate", "conceited", "confident", "confused", "considerate", 
    "content", "cool", "cooperative", "corny", "courageous", "cranky", "creepy", "crude", "cruel", "cuddly",
    "curious", "cute", "cynical", "daffy", "dashing", "dazed", "debonair", "decisive", "delicate", "delightful",
    "demanding", "dependable", "deranged", "desperate", "determined", "devilish", "diligent", "dim-witted",
    "dinky", "dirty", "discreet", "disgusting", "dizzy", "dopey", "dramatic", "dreary", "droopy", "drunk", 
    "dull", "dynamic", "eager", "earnest", "easygoing", "eccentric", "edgy", "elegant", "eloquent", "embarrassed",
    "energetic", "enigmatic", "enthusiastic", "epic", "exasperated", "excited", "exhausted", "exotic", "fabulous",
    "faint-hearted", "faithful", "fancy", "fantastic", "farting", "fearful", "fearless", "feisty", "fierce",
    "filthy", "flamboyant", "flashy", "flirty", "flustered", "foolish", "forgetful", "forgiving", "fragile", 
    "frantic", "frisky", "frustrated", "funny", "fussy", "gabby", "gargantuan", "gassy", "generous", "gentle", 
    "giggly", "glamorous", "gleeful", "gloomy", "glorious", "glowing", "goofy", "gorgeous", "graceful", 
    "gracious", "greasy", "greedy", "grimy", "grinning", "grumpy", "gullible", "gutsy", "handsome", "hardy", 
    "hasty", "haughty", "headstrong", "heartless", "hearty", "heavenly", "helpful", "heroic", "high-spirited", 
    "hilarious", "horny", "hot-headed", "huggable", "humble", "humorous", "hyper", "hysterical", "ignorant", 
    "imaginative", "immature", "impolite", "impulsive", "inattentive", "incompetent", "inconsiderate", 
    "indecent", "independent", "indignant", "insecure", "insensitive", "insightful", "intelligent", "intense",
    "interesting", "intimidating", "irritable", "jaded", "jazzy", "jealous", "jiggly", "jittery", "jolly",
    "jovial", "joyful", "juicy", "jumpy", "keen", "kind", "kinky", "knobby", "kooky", "lazy", "lewd", "lively",
    "lovable", "lucky", "luminous", "luscious", "lustful", "mad", "manic", "marvelous", "massive", "meaty",
    "melancholy", "merry", "messy", "meticulous", "mischievous", "moody", "morbid", "mysterious", "naive",
    "nasty", "naughty", "needy", "nefarious", "nervous", "nimble", "nosy", "nurturing", "nutty", "obnoxious", 
    "obscene", "obsessive", "odd", "offensive", "oily", "opinionated", "optimistic", "outrageous", "overjoyed", 
    "overwhelmed", "panicky", "passionate", "patient", "patriotic", "peaceful", "peppy", "perky", "perverted", 
    "petty", "picky", "playful", "plucky", "plump", "polite", "pompous", "popular", "powerful", "precious", 
    "prickly", "prissy", "prominent", "proud", "puzzled", "quirky", "rabid", "radiant", "rambunctious", "randy",
    "raunchy", "reassured", "reckless", "refined", "regal", "relaxed", "relentless", "reliable", "repulsive", 
    "resilient", "restless", "righteous", "rigid", "rotten", "rowdy", "rude", "sassy", "saucy", "scared", 
    "scary", "scornful", "scrappy", "selfish", "sensitive", "sexy", "shameless", "sharp", "shifty", "shiny", 
    "shocking", "shrewd", "shy", "silly", "sloppy", "sluggish", "sly", "smelly", "smooth", "snappy", "sneaky", 
    "snobby", "social", "spacious", "spicy", "spirited", "spoiled", "spunky", "squeaky", "stinky", "stubborn",
    "stunning", "suave", "subtle", "sultry", "super", "surly", "sweet", "sympathetic", "tactful", "tactless", 
    "talented", "talkative", "tame", "tasty", "teasing", "tenacious", "testy", "thankful", "thirsty", "thoughtful", 
    "timid", "tipsy", "tired", "tough", "tricky", "trusting", "truthful", "ugly", "uncanny", "unemotional", 
    "unfriendly", "ungrateful", "unkind", "unnerving", "unruly", "upbeat", "vain", "vapid", "vicious", "victorious", 
    "virtuous", "vivacious", "vulgar", "wacky", "weary", "whimsical", "wicked", "wise", "witty", "wobbly", 
    "worried", "zany", "zealous", "zippy", "zoned-out"
]

nouns = [
    "apple", "aardvark", "archer", "alien", "antelope", "artichoke", "bacon", "balloon",
    "banana", "bandit", "barnacle", "basilisk", "beach", "beaver", "bedbug", "biscuit",
    "bison", "blizzard", "blobfish", "blowfish", "booger", "book", "boot", "bottle",
    "brain", "breeze", "broccoli", "bubble", "bumblebee", "burrito", "butter", "butterfly",
    "cactus", "cabbage", "camel", "canary", "candy", "carrot", "cat", "cave", "cherry",
    "cheeseburger", "chicken", "chimney", "chipmunk", "chocolate", "cloud", "clown",
    "cobweb", "cookie", "corn", "cow", "crab", "crayon", "cucumber", "cupcake", "curtain",
    "dachshund", "dandelion", "deer", "diaper", "dinosaur", "dirt", "dodo", "dog",
    "donkey", "donut", "dragon", "dream", "duck", "dung", "eagle", "eel", "eggplant",
    "elephant", "elf", "emu", "eraser", "eye", "fart", "feather", "ferret", "fetus",
    "firecracker", "fish", "flamingo", "flea", "fog", "foot", "fox", "frog", "fudge",
    "giraffe", "glacier", "goblin", "goat", "gobstopper", "goose", "gorilla", "grasshopper",
    "gremlin", "guitar", "hamster", "hamburger", "hedgehog", "hermit", "hippopotamus",
    "honey", "hornet", "horse", "hotdog", "iguana", "inchworm", "island", "jellybean",
    "jellyfish", "kangaroo", "ketchup", "kitten", "koala", "kumquat", "ladybug", "lamp",
    "lemon", "leopard", "lettuce", "lightning", "lion", "lizard", "llama", "lobster",
    "lollipop", "macaroni", "magnet", "mango", "manatee", "marshmallow", "mattress", "mole",
    "moose", "mosquito", "moth", "mountain", "mouse", "muffin", "mushroom", "narwhal",
    "nectarine", "newt", "ninja", "noodle", "nose", "nutmeg", "octopus", "ogre", "onion",
    "ostrich", "otter", "owl", "pancake", "panda", "panther", "parrot", "peach", "peanut",
    "pebble", "pelican", "penguin", "pickle", "pigeon", "pineapple", "pizza", "platypus",
    "poodle", "popcorn", "potato", "pumpkin", "puppy", "quack", "quagmire", "quartz",
    "quokka", "quoll", "rabbit", "raccoon", "radish", "rainbow", "raven", "rhino", "rhubarb",
    "robot", "rocket", "rooster", "rose", "salamander", "sandwich", "sasquatch", "sausage",
    "scorpion", "seagull", "seal", "shark", "sheep", "skunk", "sloth", "slug", "snail",
    "snake", "snowman", "sock", "socks", "spaghetti", "spider", "squid", "starfish", "stork",
    "strawberry", "sunflower", "swan", "swordfish", "taco", "tangerine", "tapir", "tarantula",
    "tiger", "toad", "toilet", "tomato", "tornado", "toucan", "trampoline", "trashcan",
    "troll", "tulip", "turtle", "unicorn", "urchin", "vampire", "velociraptor", "vulture",
    "walrus", "watermelon", "weasel", "whale", "whippet", "wig", "wildcat", "willow", 
    "wind", "wombat", "worm", "yak", "yeti", "yogurt", "zebra", "zombie", "zeppelin", 
    "baboon", "bamboo", "banshee", "barrel", "bat", "bath", "bean", "beard", "beetle", 
    "belly", "bench", "bicycle", "bikini", "blanket", "blimp", "blizzard", "blouse", 
    "boar", "boat", "body", "bologna", "bonfire", "bone", "boogeyman", "boomerang", 
    "boots", "bread", "brick", "broccoli", "broom", "bubblegum", "buck", "bull", 
    "burger", "butt", "buzzard", "cabbage", "cannoli", "cape", "castle", "catfish", 
    "caterpillar", "chain", "chair", "cheese", "cheetah", "cherry", "chihuahua", "chimera", 
    "clam", "cliff", "clownfish", "club", "cobra", "coconut", "coffee", "cookie", "cougar", 
    "cowboy", "cowgirl", "cracker", "cranberry", "crow", "crustacean", "cuddlefish", 
    "cup", "cyclone", "dachshund", "dagger", "daisy", "dawn", "dewdrop", "diamond", 
    "dingo", "dirtbag", "diva", "dogfish", "dolphin", "doormat", "dove", "dragonfruit", 
    "dragonfly", "dude", "dungeon", "eagle", "eclair", "eel", "egg", "eggnog", 
    "eiffel", "elf", "emperor", "energy", "fang", "firefly", "fishstick", "flame", 
    "flapjack", "flute", "fogbank", "footstool", "fork", "fossil", "foxhound", "fritter", 
    "galleon", "game", "garden", "garlic", "giraffe", "gnome", "goatee", "goatfish", 
    "gooseberry", "gravy", "griffin", "grizzly", "guacamole", "gumball", "gummy", 
    "ham", "hammerhead", "hatchling", "hedge", "heron", "hippie", "hotcake", "hummingbird", 
    "hunk", "iceberg", "iguana", "ink", "jackal", "jalapeno", "jelly", "jock", 
    "juice", "jumbo", "jump", "kangaroo", "karate", "kelp", "kettle", "kiwi", "koala", 
    "kumquat", "ladder", "ladyfinger", "lagoon", "lamb", "lawn", "lawnmower", "leaf", 
    "leprechaun", "licorice", "lime", "llama", "log", "lumberjack", "mace", "magpie", 
    "mannequin", "marble", "mare", "marsh", "meadow", "melon", "mermaid", "minotaur", 
    "mocha", "monkey", "monster", "moth", "muffler", "mustard", "nacho", "nanny", 
    "napkin", "needle", "neon", "nightmare", "noodle", "nymph", "oasis", "octopus", 
    "olive", "onion", "orchid", "ostrich", "oven", "owl", "oxygen", "paint", 
    "palm", "pan", "paper", "parrot", "pastrami", "peacock", "peach", "penguin", 
    "pickle", "pie", "pilot", "pina", "piranha", "planet", "platypus", "plum", 
    "plunger", "pomegranate", "pony", "poodle", "porcupine", "porridge", "prawn", 
    "princess", "prune", "puffin", "pumpkin", "quail", "quiche", "rabbit", "raccoon", 
    "rain", "raven", "razor", "reef", "reindeer", "rhinoceros", "ring", "robot", 
    "rock", "rooster", "rose", "round", "rum", "salami", "sapphire", "satchel", 
    "sauce", "scallion", "scarecrow", "scarf", "scorpion", "seaweed", "shampoo", 
    "shark", "sheepdog", "shortcake", "shrimp", "skull", "slippers", "slug", "snout", 
    "soda", "sockeye", "sparrow", "spoon", "sprout", "spud", "squid", "squirrel", 
    "stalker", "star", "stinger", "stoat", "straw", "stream", "sugar", "sunrise", 
    "swamp", "swine", "syrup", "tabby", "taco", "tail", "tank", "tarantula", 
    "toadstool", "tomcat", "topaz", "tornado", "toupee", "trout", "truffle", 
    "tulip", "tumbleweed", "tuna", "turtleneck", "urchin", "vanilla", "viper", 
    "vixen", "vulture", "walnut", "wasabi", "water", "weasel", "whale", "whisker", 
    "whistle", "wig", "willow", "wombat", "yacht", "yak", "yam", "yawn", "yeast", 
    "yeti", "yogurt", "zeppelin", "zombie", "zucchini"
]

print(len(adjectives))
print(len(nouns))